import Foundation

func main() {
    do {
        try Day1().main()
    } catch {
        fatalError("Failed with error \(error)")
    }
}

main()
